apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uwy11z42z-nodejs 
  janus-idp.io/tekton: uwy11z42z-nodejs
  backstage.io/kubernetes-id: uwy11z42z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uwy11z42z-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  